@baseURL = http://localhost:3000
@route = /[any]
@url = {{baseURL}}{{route}}

# @name base
GET {{url}}

###

# @name param
GET {{url}}/32

### 
# @name example
POST {{url}}/in
Content-Type: application/json

{
    "token": {{param.response.body.token}}
}